version: '{build}'
image: Visual Studio 2019
configuration: Release

environment:
  # set version number for plug-in and yak package
  assembly_version: 1.0.1
  yak_package_version: $(assembly_version)

  # set auth token for yak
  # > yak login --ci
  YAK_TOKEN:
    secure: rR4brxF6Yv347W0az21iXGEF8Y+ETSw3oJkJwsOSmqcAfBL1HobZe/k/qT1d3L2ZeaJwhj2msTpB7urWvI9eAfEpU1cRekjfE9Vnz51XIecmEWdiR+7zkikTF5aPEffrauvJvP3u2t9SLw5Ui+FK+B1Hk3tZiqn63T3GBLSgff9mxTeeRR1arty3nuZclux1hfgWnGFEOyTu1SsCMlTmNCQd/kkgxU2MEHVn7KiP9Ib+al9oJWFskSduRRu9C6IijT1C+qfg0qtNgDLqic2D/Cv5mWUj1H02NiFxUVbzcBZrbiw0aWbU37KqcwsM3/shoJz5g0V8gWqqHWC3MT6+xPyX3TH4U4xUGoLc8gZ6KYepmcwyByacxbTRDqPPYyN1lCvqdgYQTxl7pFUsvWYSOx/0NX/3Ojf5xn8bsZvx3JxkIddyR7fwC973z5fxGjSZGFh6ECf4Q2aQDFboqIc/SQpYNRaBnoLL1Nw1Hp0qgTAszf51SEIl6ISLGwC2PTD59qmltvR72e8RI3zE9oq/OP9RPJTqgaxS1nyAlHOA3n4BgSsBZvm3JJOXsZn1GfUALbN/gn2Cfdsf6WWt8JQ4nV55pvKnIbzNIrhmFIx4M2Zadhfd5lhrscF7irdl/9atkbeCdmC9BDO1mNNtN93KFD8YTw/lWJbLeYS24GI2ujk=

assembly_info:
  patch: true
  file: 'Properties\AssemblyInfo.cs'
  assembly_version: $(assembly_version)
  assembly_informational_version: $(yak_package_version)

# compile plug-in
before_build:
  - nuget restore

build:
  project: GhCanvasViewport.sln
  verbosity: minimal

# build yak package
before_deploy:
  - curl -fSLo yak.exe https://files.mcneel.com/yak/tools/latest/yak.exe
    && yak.exe version
    && copy bin\GhCanvasViewport.gha dist
    && cd dist
    && ..\yak.exe build --version "%yak_package_version%" --platform win
    && cd ..

# publish to rhino package manager (master branch only)
deploy_script:
  - IF "%APPVEYOR_REPO_BRANCH%"=="master" (
      for %%i in (dist\*.yak) do yak.exe push %%i
    )
